// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlrxwpvhyqvvimaoern.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bHJ4d3B2aHlxdnZpbWFvZXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDkzOTIsImV4cCI6MjA2Nzg4NTM5Mn0.ILS-QXOV1RKiXK94QNUvOEkdGhms2NfG7gwI11ZMPhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});